version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    ports:
      - "3001:3001"

networks:
  app-network:
    driver: bridge
