version: "3.8"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    ports:
      - "5002:5002"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./backend/.env
    networks:
      - app-network
    ports:
      - "3001:3001"

networks:
  app-network:
    driver: bridge
